namespace Proton.VM.IL
{
    public enum ILExtendedOpcode : byte
    {
        ArgList = 0x00,
        Ceq = 0x01,
        Cgt = 0x02,
        Cgt_Un = 0x03,
        Clt = 0x04,
        Clt_Un = 0x05,
        LdFtn = 0x06,
        LdVirtFtn = 0x07,
        // N/A								= 0x08,
        LdArg = 0x09,
        LdArgA = 0x0A,
        StArg = 0x0B,
        LdLoc = 0x0C,
        LdLocA = 0x0D,
        StLoc = 0x0E,
        LocAlloc = 0x0F,
        // N/A								= 0x10,
        EndFilter = 0x11,
        Unaligned__ = 0x12,
        Volatile__ = 0x13,
        Tail__ = 0x14,
        InitObj = 0x15,
        Constrained__ = 0x16,
        CpBlk = 0x17,
        InitBlk = 0x18,
        No__ = 0x19,
        ReThrow = 0x1A,
        // N/A								= 0x1B,
        SizeOf = 0x1C,
        RefAnyType = 0x1D,
        ReadOnly__ = 0x1E,
    }
}
