#include "IDT.h"
#include "../PIC.h"

extern "C" {
void* gIDTRegisterPointer = nullptr;
void IDTEmptyInterrupt(IDT::InterruptRegisters pRegisters);

#include "IDTExternalStubs.h" // Must remain here
}


namespace IDT
{
	const uint16_t SELECTOR_PRIVILEDGELEVEL_RING0 = 0x0000;
	const uint16_t SELECTOR_PRIVILEDGELEVEL_RING1 = 0x0001;
	const uint16_t SELECTOR_PRIVILEDGELEVEL_RING2 = 0x0002;
	const uint16_t SELECTOR_PRIVILEDGELEVEL_RING3 = 0x0003;
	const uint16_t SELECTOR_TABLEINDEX = 0x0004;
	const uint16_t SELECTOR_DESCRIPTORINDEX = 0x0008;

	const uint8_t TYPE_TASK386GATE32BIT = 0x05;
	const uint8_t TYPE_INTERRUPT286GATE16BIT = 0x06;
	const uint8_t TYPE_TRAP286GATE16BIT = 0x07;
	const uint8_t TYPE_INTERRUPT386GATE32BIT = 0x0E;
	const uint8_t TYPE_TRAP386GATE32BIT = 0x0F;
	const uint8_t TYPE_PRESENT = 0x80;

	Register sRegister;
	Descriptor* sDescriptors = nullptr;
	uint32_t sDescriptorCount = 0;
	Callback* sCallbacks = nullptr;
	bool* sPending = nullptr;


	void CPUInterruptHandler(InterruptRegisters pRegisters)
	{
		char buf[128];
		sprintf(buf, "CPU Exception: %d", (int)pRegisters.int_no);
		Panic(buf);
	}

	void Startup()
	{
		sDescriptorCount = 256;
		sDescriptors = new Descriptor[sDescriptorCount];
		sCallbacks = new Callback[sDescriptorCount];
		sPending = new bool[sDescriptorCount];
		for (uint32_t index = 0; index < sDescriptorCount; ++index)
		{
			sCallbacks[index] = nullptr;
			sPending[index] = false;
		}

	    sRegister.Limit = (sizeof(Descriptor) * sDescriptorCount) - 1;
		sRegister.Address = (size_t)&sDescriptors[0];

		// Reserved for CPU
		sDescriptors[0x00].Set((uint32_t)IDTISR00, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x01].Set((uint32_t)IDTISR01, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x02].Set((uint32_t)IDTISR02, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x03].Set((uint32_t)IDTISR03, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x04].Set((uint32_t)IDTISR04, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x05].Set((uint32_t)IDTISR05, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x06].Set((uint32_t)IDTISR06, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x07].Set((uint32_t)IDTISR07, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x08].Set((uint32_t)IDTISR08, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x09].Set((uint32_t)IDTISR09, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x0A].Set((uint32_t)IDTISR0A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x0B].Set((uint32_t)IDTISR0B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x0C].Set((uint32_t)IDTISR0C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x0D].Set((uint32_t)IDTISR0D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x0E].Set((uint32_t)IDTISR0E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x0F].Set((uint32_t)IDTISR0F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x10].Set((uint32_t)IDTISR10, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x11].Set((uint32_t)IDTISR11, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x12].Set((uint32_t)IDTISR12, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x13].Set((uint32_t)IDTISR13, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x14].Set((uint32_t)IDTISR14, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x15].Set((uint32_t)IDTISR15, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x16].Set((uint32_t)IDTISR16, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x17].Set((uint32_t)IDTISR17, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x18].Set((uint32_t)IDTISR18, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x19].Set((uint32_t)IDTISR19, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x1A].Set((uint32_t)IDTISR1A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x1B].Set((uint32_t)IDTISR1B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x1C].Set((uint32_t)IDTISR1C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x1D].Set((uint32_t)IDTISR1D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x1E].Set((uint32_t)IDTISR1E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x1F].Set((uint32_t)IDTISR1F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		// Reserved for IRQ
		sDescriptors[0x20].Set((uint32_t)IDTIRQ00, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x21].Set((uint32_t)IDTIRQ01, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x22].Set((uint32_t)IDTIRQ02, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x23].Set((uint32_t)IDTIRQ03, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x24].Set((uint32_t)IDTIRQ04, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x25].Set((uint32_t)IDTIRQ05, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x26].Set((uint32_t)IDTIRQ06, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x27].Set((uint32_t)IDTIRQ07, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x28].Set((uint32_t)IDTIRQ08, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x29].Set((uint32_t)IDTIRQ09, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x2A].Set((uint32_t)IDTIRQ0A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x2B].Set((uint32_t)IDTIRQ0B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x2C].Set((uint32_t)IDTIRQ0C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x2D].Set((uint32_t)IDTIRQ0D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x2E].Set((uint32_t)IDTIRQ0E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x2F].Set((uint32_t)IDTIRQ0F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		// Usable
		sDescriptors[0x30].Set((uint32_t)IDTISR30, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x31].Set((uint32_t)IDTISR31, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x32].Set((uint32_t)IDTISR32, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x33].Set((uint32_t)IDTISR33, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x34].Set((uint32_t)IDTISR34, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x35].Set((uint32_t)IDTISR35, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x36].Set((uint32_t)IDTISR36, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x37].Set((uint32_t)IDTISR37, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x38].Set((uint32_t)IDTISR38, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x39].Set((uint32_t)IDTISR39, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x3A].Set((uint32_t)IDTISR3A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x3B].Set((uint32_t)IDTISR3B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x3C].Set((uint32_t)IDTISR3C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x3D].Set((uint32_t)IDTISR3D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x3E].Set((uint32_t)IDTISR3E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x3F].Set((uint32_t)IDTISR3F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x40].Set((uint32_t)IDTISR40, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x41].Set((uint32_t)IDTISR41, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x42].Set((uint32_t)IDTISR42, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x43].Set((uint32_t)IDTISR43, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x44].Set((uint32_t)IDTISR44, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x45].Set((uint32_t)IDTISR45, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x46].Set((uint32_t)IDTISR46, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x47].Set((uint32_t)IDTISR47, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x48].Set((uint32_t)IDTISR48, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x49].Set((uint32_t)IDTISR49, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x4A].Set((uint32_t)IDTISR4A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x4B].Set((uint32_t)IDTISR4B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x4C].Set((uint32_t)IDTISR4C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x4D].Set((uint32_t)IDTISR4D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x4E].Set((uint32_t)IDTISR4E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x4F].Set((uint32_t)IDTISR4F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x50].Set((uint32_t)IDTISR50, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x51].Set((uint32_t)IDTISR51, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x52].Set((uint32_t)IDTISR52, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x53].Set((uint32_t)IDTISR53, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x54].Set((uint32_t)IDTISR54, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x55].Set((uint32_t)IDTISR55, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x56].Set((uint32_t)IDTISR56, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x57].Set((uint32_t)IDTISR57, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x58].Set((uint32_t)IDTISR58, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x59].Set((uint32_t)IDTISR59, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x5A].Set((uint32_t)IDTISR5A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x5B].Set((uint32_t)IDTISR5B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x5C].Set((uint32_t)IDTISR5C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x5D].Set((uint32_t)IDTISR5D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x5E].Set((uint32_t)IDTISR5E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x5F].Set((uint32_t)IDTISR5F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x60].Set((uint32_t)IDTISR60, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x61].Set((uint32_t)IDTISR61, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x62].Set((uint32_t)IDTISR62, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x63].Set((uint32_t)IDTISR63, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x64].Set((uint32_t)IDTISR64, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x65].Set((uint32_t)IDTISR65, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x66].Set((uint32_t)IDTISR66, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x67].Set((uint32_t)IDTISR67, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x68].Set((uint32_t)IDTISR68, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x69].Set((uint32_t)IDTISR69, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x6A].Set((uint32_t)IDTISR6A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x6B].Set((uint32_t)IDTISR6B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x6C].Set((uint32_t)IDTISR6C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x6D].Set((uint32_t)IDTISR6D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x6E].Set((uint32_t)IDTISR6E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x6F].Set((uint32_t)IDTISR6F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x70].Set((uint32_t)IDTISR70, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x71].Set((uint32_t)IDTISR71, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x72].Set((uint32_t)IDTISR72, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x73].Set((uint32_t)IDTISR73, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x74].Set((uint32_t)IDTISR74, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x75].Set((uint32_t)IDTISR75, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x76].Set((uint32_t)IDTISR76, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x77].Set((uint32_t)IDTISR77, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x78].Set((uint32_t)IDTISR78, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x79].Set((uint32_t)IDTISR79, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x7A].Set((uint32_t)IDTISR7A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x7B].Set((uint32_t)IDTISR7B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x7C].Set((uint32_t)IDTISR7C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x7D].Set((uint32_t)IDTISR7D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x7E].Set((uint32_t)IDTISR7E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x7F].Set((uint32_t)IDTISR7F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x80].Set((uint32_t)IDTISR80, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x81].Set((uint32_t)IDTISR81, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x82].Set((uint32_t)IDTISR82, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x83].Set((uint32_t)IDTISR83, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x84].Set((uint32_t)IDTISR84, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x85].Set((uint32_t)IDTISR85, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x86].Set((uint32_t)IDTISR86, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x87].Set((uint32_t)IDTISR87, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x88].Set((uint32_t)IDTISR88, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x89].Set((uint32_t)IDTISR89, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x8A].Set((uint32_t)IDTISR8A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x8B].Set((uint32_t)IDTISR8B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x8C].Set((uint32_t)IDTISR8C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x8D].Set((uint32_t)IDTISR8D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x8E].Set((uint32_t)IDTISR8E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x8F].Set((uint32_t)IDTISR8F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x90].Set((uint32_t)IDTISR90, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x91].Set((uint32_t)IDTISR91, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x92].Set((uint32_t)IDTISR92, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x93].Set((uint32_t)IDTISR93, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x94].Set((uint32_t)IDTISR94, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x95].Set((uint32_t)IDTISR95, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x96].Set((uint32_t)IDTISR96, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x97].Set((uint32_t)IDTISR97, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x98].Set((uint32_t)IDTISR98, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x99].Set((uint32_t)IDTISR99, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x9A].Set((uint32_t)IDTISR9A, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x9B].Set((uint32_t)IDTISR9B, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x9C].Set((uint32_t)IDTISR9C, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x9D].Set((uint32_t)IDTISR9D, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x9E].Set((uint32_t)IDTISR9E, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0x9F].Set((uint32_t)IDTISR9F, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA0].Set((uint32_t)IDTISRA0, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA1].Set((uint32_t)IDTISRA1, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA2].Set((uint32_t)IDTISRA2, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA3].Set((uint32_t)IDTISRA3, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA4].Set((uint32_t)IDTISRA4, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA5].Set((uint32_t)IDTISRA5, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA6].Set((uint32_t)IDTISRA6, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA7].Set((uint32_t)IDTISRA7, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA8].Set((uint32_t)IDTISRA8, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xA9].Set((uint32_t)IDTISRA9, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xAA].Set((uint32_t)IDTISRAA, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xAB].Set((uint32_t)IDTISRAB, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xAC].Set((uint32_t)IDTISRAC, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xAD].Set((uint32_t)IDTISRAD, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xAE].Set((uint32_t)IDTISRAE, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xAF].Set((uint32_t)IDTISRAF, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB0].Set((uint32_t)IDTISRB0, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB1].Set((uint32_t)IDTISRB1, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB2].Set((uint32_t)IDTISRB2, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB3].Set((uint32_t)IDTISRB3, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB4].Set((uint32_t)IDTISRB4, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB5].Set((uint32_t)IDTISRB5, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB6].Set((uint32_t)IDTISRB6, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB7].Set((uint32_t)IDTISRB7, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB8].Set((uint32_t)IDTISRB8, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xB9].Set((uint32_t)IDTISRB9, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xBA].Set((uint32_t)IDTISRBA, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xBB].Set((uint32_t)IDTISRBB, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xBC].Set((uint32_t)IDTISRBC, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xBD].Set((uint32_t)IDTISRBD, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xBE].Set((uint32_t)IDTISRBE, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xBF].Set((uint32_t)IDTISRBF, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC0].Set((uint32_t)IDTISRC0, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC1].Set((uint32_t)IDTISRC1, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC2].Set((uint32_t)IDTISRC2, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC3].Set((uint32_t)IDTISRC3, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC4].Set((uint32_t)IDTISRC4, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC5].Set((uint32_t)IDTISRC5, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC6].Set((uint32_t)IDTISRC6, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC7].Set((uint32_t)IDTISRC7, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC8].Set((uint32_t)IDTISRC8, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xC9].Set((uint32_t)IDTISRC9, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xCA].Set((uint32_t)IDTISRCA, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xCB].Set((uint32_t)IDTISRCB, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xCC].Set((uint32_t)IDTISRCC, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xCD].Set((uint32_t)IDTISRCD, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xCE].Set((uint32_t)IDTISRCE, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xCF].Set((uint32_t)IDTISRCF, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD0].Set((uint32_t)IDTISRD0, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD1].Set((uint32_t)IDTISRD1, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD2].Set((uint32_t)IDTISRD2, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD3].Set((uint32_t)IDTISRD3, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD4].Set((uint32_t)IDTISRD4, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD5].Set((uint32_t)IDTISRD5, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD6].Set((uint32_t)IDTISRD6, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD7].Set((uint32_t)IDTISRD7, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD8].Set((uint32_t)IDTISRD8, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xD9].Set((uint32_t)IDTISRD9, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xDA].Set((uint32_t)IDTISRDA, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xDB].Set((uint32_t)IDTISRDB, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xDC].Set((uint32_t)IDTISRDC, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xDD].Set((uint32_t)IDTISRDD, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xDE].Set((uint32_t)IDTISRDE, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xDF].Set((uint32_t)IDTISRDF, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE0].Set((uint32_t)IDTISRE0, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE1].Set((uint32_t)IDTISRE1, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE2].Set((uint32_t)IDTISRE2, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE3].Set((uint32_t)IDTISRE3, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE4].Set((uint32_t)IDTISRE4, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE5].Set((uint32_t)IDTISRE5, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE6].Set((uint32_t)IDTISRE6, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE7].Set((uint32_t)IDTISRE7, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE8].Set((uint32_t)IDTISRE8, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xE9].Set((uint32_t)IDTISRE9, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xEA].Set((uint32_t)IDTISREA, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xEB].Set((uint32_t)IDTISREB, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xEC].Set((uint32_t)IDTISREC, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xED].Set((uint32_t)IDTISRED, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xEE].Set((uint32_t)IDTISREE, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xEF].Set((uint32_t)IDTISREF, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF0].Set((uint32_t)IDTISRF0, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF1].Set((uint32_t)IDTISRF1, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF2].Set((uint32_t)IDTISRF2, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF3].Set((uint32_t)IDTISRF3, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF4].Set((uint32_t)IDTISRF4, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF5].Set((uint32_t)IDTISRF5, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF6].Set((uint32_t)IDTISRF6, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF7].Set((uint32_t)IDTISRF7, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF8].Set((uint32_t)IDTISRF8, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xF9].Set((uint32_t)IDTISRF9, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xFA].Set((uint32_t)IDTISRFA, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xFB].Set((uint32_t)IDTISRFB, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xFC].Set((uint32_t)IDTISRFC, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xFD].Set((uint32_t)IDTISRFD, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		// Reserved for LAPIC Timers
		sDescriptors[0xFE].Set((uint32_t)IDTISRFE, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
		sDescriptors[0xFF].Set((uint32_t)IDTISRFF, SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);

		gIDTRegisterPointer = &sRegister;
		IDTUpdateRegister();

		for (uint8_t interrupt = 0; interrupt < IRQ_BASE; ++interrupt) sCallbacks[interrupt] = CPUInterruptHandler;
	}

	void RegisterCallback(uint8_t pInterrupt, Callback pCallback)
	{
		sCallbacks[pInterrupt] = pCallback;
	}

	void Schedule(uint8_t pInterrupt)
	{
		sPending[pInterrupt] = true;
	}

	void WaitFor(uint8_t pInterrupt)
	{
		while (sPending[pInterrupt]);
	}

	void SetEmptyInterrupt(uint8_t pInterrupt)
	{
		sDescriptors[pInterrupt].Set(reinterpret_cast<uint32_t>(IDTEmptyInterrupt), SELECTOR_DESCRIPTORINDEX, TYPE_INTERRUPT386GATE32BIT | TYPE_PRESENT);
	}
}

extern "C" {
void IDTISRHandler(IDT::InterruptRegisters pRegisters) 
{
	IDT::sPending[pRegisters.int_no] = false;
    IDT::Callback callback = IDT::sCallbacks[pRegisters.int_no];
    if (callback) callback(pRegisters);
}

void IDTIRQHandler(IDT::InterruptRegisters pRegisters)
{
	IDT::sPending[IDT::IRQ_BASE + pRegisters.int_no] = false;
    IDT::Callback callback = IDT::sCallbacks[IDT::IRQ_BASE + pRegisters.int_no];
    if (callback) callback(pRegisters);
	PIC::ResetInterrupts(pRegisters.int_no >= 9);
}
}
